### ISSUE TITLE
example usage with new tokio-postgres?

### ISSUE THREAD

**Issue by jspeis** [khuey/bb8#15]
Would love to use bb8 with the new tokio-postgres v0.4.0-rc.2. Would be great if there were a was a small usage example that you could share in the readme? Great work!

**Comment by khuey** [comment]
Take a look at `postgres/examples/static_select.rs`.

**Comment by jspeis** [comment]
Thanks!

**Comment by khuey** [comment]
Worth noting that bb8 is still on a private fork of tokio-postgres because I have an outstanding PR, but that fork is from v0.4.0-rc2.

**Comment by jspeis** [comment]
Ah, I see. Just saw [sfackler's comment](https://github.com/sfackler/rust-postgres/pull/424) on the PR. If that error ends up in bb8 then it would be otherwise ok with v0.4.0-rc2?

**Comment by khuey** [comment]
I dealt with this by changing the API a bit. The changes are now on crates.io as version 0.3.0
