### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by ckatzer4** [khuey/bb8#17]
Hello and thanks for starting this much-needed crate.

I'll be using `bb8` as part of a personal project, but I'd like to be able to pull this from crates.io instead of directly from git.  That will also help with versioning in case there's an API change.

Are there any plans for publishing the `bb8` crate soon?

**Comment by khuey** [comment]
https://crates.io/crates/bb8

**Comment by khuey** [comment]
I'll do the adapter crates later today.
