### ISSUE TITLE
Implement `Error` for `bb8::RunError`

### ISSUE THREAD

**Issue by s-panferov** [khuey/bb8#18]
Hello, thanks for the library. Is it possible to implement [the Error](https://doc.rust-lang.org/nightly/std/error/trait.Error.html) trait for the [RunError](https://docs.rs/bb8/0.3.0/bb8/enum.RunError.html)? This would allow better cooperation with the `failure` crate.

**Comment by khuey** [comment]
Yeah, it's not hard to do. Do you want to take a stab at it?
