### ISSUE TITLE
Use Config struct instead of string for Postgres connection 

### ISSUE THREAD

**Issue by jannschu** [khuey/bb8#28]
Hi,

I would suggest to use the `Config` struct from tokio_postgres to specify connection details instead of passing a string "postgres://...".

Currently, the string is passed to `connect` from tokio_postgres, which is a helper function. There, the string is parsed to a `Config` struct.

So the api would change from `::new("postgres://....")` to `::new("postgres://...".into())`.

This saves parsing a string if the connection details are not in the correct format. At the moment I have to assemble a string in the expected format which then gets parsed immediately.

I think this is also how r2d2 works.

**Comment by khuey** [comment]
Sure, sounds find. Do you want to send a PR?

**Comment by khuey** [comment]
Fixed by c4061595e7d093c7067105f963a10dc949fa8d7b
