### ISSUE TITLE
Should Builder::build return a future?

### ISSUE THREAD

**Issue by jannschu** [khuey/bb8#30]
Hi,

when I run

```rust
let pool = bb8::Pool::builder().build(manager)
```

without wrapping into `future::lazy` the program crashes. The reason is, that `Pool::new_inner` schedules a task to reap connections.

I suggest to do this the first time the future is polled.

~~If you agree I could try to implement this.~~ Edit: I will try something else first.

**Comment by khuey** [comment]
It's easy enough to wrap it in a `lazy` yourself so I'm not very inclined to do this.

**Comment by djc** [comment]
`Builder::build()` now returns a `Future`.
