### ISSUE TITLE
Migrate to (std::)futures 0.3 and tokio 0.2

### ISSUE THREAD

**Issue by ohmyarch** [khuey/bb8#31]
https://github.com/rust-lang/rust/pull/63209#issuecomment-523113079
https://tokio.rs/blog/2019-08-alphas/

**Comment by ohmyarch** [comment]
https://github.com/sfackler/rust-postgres/tree/std-futures/tokio-postgres

**Comment by pimeys** [comment]
Could we also change the interface a bit to the direction of how r2d2 works, could it be possible now with `std::future`, async/await and `Pin`?

So we could be able to use it in a more synchronous-looking manner:

```rust
impl AsyncConnector for Asynchronous {
    fn run(&self, query: Arc<String>) -> FutureObj<'static, crate::Result<serde_json::Value>> {
	let fut = async move {
            let mut client = self.pool.get().await?;
            let stmt = client.prepare(query.as_str()).await?;
            let rows = client.query(&stmt, &[]).collect().await?;

            Ok(rows.into_json()?)
        };

        FutureObj::new(Box::new(fut))
    }
}
```

**Comment by githubaccount624** [comment]
Hi @khuey I was wondering if you ever got a chance to check out tokio-postgres's futures branch and if it could work with bb8.

**Comment by djc** [comment]
I've got an initial attempt in #37 that's most of the way there.

**Comment by ohmyarch** [comment]
tokio-postgres v0.5.0-alpha.1 which uses std::futures::Future and async/await syntax is out.

**Comment by ohmyarch** [comment]
async/await syntax stabilized in 1.39

**Comment by djc** [comment]
This is done.
