### ISSUE TITLE
bb8 and bb8-postgres: difference?

### ISSUE THREAD

**Issue by apiraino** [khuey/bb8#32]
Hi,

I am running a small backend with Hyper, I was investigating this library to have an async threadpool.

I was wondering what's the difference between `bb8` and `bb8-postgres`.

Also, I join the others in asking a bit more documentation and examples (tokio itself is a bit hard to grasp for newbies). The example for Postgres looks like to rely on unreleased version of the library. 

EDIT: also, do you have plans to push forward the development of the tokio-based branch of `bb8` (now that async-std is out)?

Thank you!

**Comment by khuey** [comment]
> 
> 
> Hi,
> 
> I am running a small backend with Hyper, I was investigating this library to have an async threadpool.
> 
> I was wondering what's the difference between `bb8` and `bb8-postgres`.

`bb8` is the backend-agnostic parts of the library, and `bb8-postgres` contains the postgres specific parts. `bb8` is not usable on its own.

> Also, I join the others in asking a bit more documentation and examples (tokio itself is a bit hard to grasp for newbies). The example for Postgres looks like to rely on unreleased version of the library.

Anything in particular that's confusing to you?

`tokio-postgres` unfortunately has not done a real release on crates.io for almost 2 years so that part is somewhat unavoidable.

> EDIT: also, do you have plans to push forward the development of the tokio-based branch of `bb8` (now that async-std is out)?

I plan to continue depending on whatever the `rust-postgres` folks are depending on which I expect to remain tokio for the forseeable future.

**Comment by apiraino** [comment]
Hi, thanks for the reply.

> Anything in particular that's confusing to you?

Basically two things.

1) As I mentioned, not being able to build `bb8` without using a stable / released version of `bb8` itself. The examples depend on a `bb8` path that points to the master branch (`0.3.2-pre`) which is not released.
Now, I could clone the repo, build locally `bb8`, build my backend against that, but I don't feel comfortable pushing to a production environment such a hacked build workflow (or perhaps I'm missing something). I would love to be able to try `bb8` with a simple `$ cargo add bb8 bb8-postgres`. A bare README file guiding through the basic steps would be surely appreciated.

2) The [hyper example](https://github.com/khuey/bb8/blob/master/postgres/examples/hyper.rs) looks (to my newbie eyes) a bit barebone in that there is no decoupling of server setup and the DB pool code. In a more real-life example, I would start Hyper passing it a [Service](https://docs.rs/hyper/0.12.33/hyper/service/trait.Service.html) that could manage a single request or act as a router for multiple endpoints. In this scenario, would you suggest passing to `service_fn()` the whole DB pool or just a connection? Again, here's [an example](https://apiraino.github.io/2019/07/18/hyper.html#part_3) of what I mean.

> tokio-postgres unfortunately has not done a real release on crates.io for almost 2 years so that part is somewhat unavoidable.

I see. I also see there's a 0.4.0rc in the works recently, perhaps we're not far from a new release. 

In the end, for the time being, I took a slightly different approach. I'm using the sync r2d2 threadpool and passing it on to any Future that needs a DB connection: some notes about that [here](https://apiraino.github.io/2019/08/28/hyper-service.html#part_2).

As I'm trying to figure out the whole async perf advantages scenario and whatnot, I'm not sure whether using `bb8` (or any async threadpool, for the matter) would give me significant advantages. I'd need some bench or real life cases before.

**Comment by apiraino** [comment]
closing because there's nothing actionable here. Will try the new release
