### ISSUE TITLE
why does tokio.run always need 30s to finish?

### ISSUE THREAD

**Issue by xudesheng** [khuey/bb8#36]
even with the simple example, tokio.run always takes at least 30s to finish. Looks like it ends with time-out? is there any way to finish it after all futures finish?

```
time ../target/debug/examples/static_select
```
Output:
```
real    0m30.328s
user    0m0.017s
sys     0m0.010s
```
Example `txn` has similar outcome.
```
time ../target/debug/examples/txn
```
Output:
```
real    0m30.021s
user    0m0.017s
sys     0m0.010s
```
But "result: 1" can be printed out very quickly. I just couldn't figure out why tokio.run needs 30s to finish.

**Comment by elpiel** [comment]
Usually a time-out is thrown when the credentials are wrong. It doesn't connects initially to check if the credentials are correct. Have you checked them?

**Comment by djc** [comment]
The analysis in https://github.com/khuey/bb8/issues/36#issuecomment-554887821 sounds correct to me. Closing for lack of further feedback.
