### ISSUE TITLE
Clarify maintenance status going forward

### ISSUE THREAD

**Issue by djc** [khuey/bb8#49]
Hi @khuey,

Since this repo hasn't been very active lately, and I need some pooling implementation that works with async/await and (ideally) has a released version on crates.io, I'd like to know what your plans are going forward. (It looks like many people might be in a similar situation since async/await has landed.) I like bb8 and as you've seen I'm happy to contribute to it, but if you don't have time for code reviews and releasing, I want to make sure I spend my time/energy wisely.

As previously mentioned, I'd be happy to help with maintenance. However, if you don't really have time to work on this crate outside some limited purpose (like, conceivably, your day job), please clarify this intention so that I can plan accordingly.

Thanks for the good code and enjoy any holiday time!

**Comment by khuey** [comment]
I'm not using this library myself anymore (because I'm not doing database stuff) so I'm not paying a lot of attention to it unfortunately.

I'm happy to add you as a maintainer and give you push access (and the ability to do crates.io releases if I can figure that out too) if you like.

**Comment by djc** [comment]
That would be nice! Do you still want to be involved at all? Otherwise you can also just transfer ownership of the repo (probably after adding me on crates.io). Also, thanks for the quick response!

**Comment by djc** [comment]
@khuey I don't think you've added me on crates.io yet, can you do that?

Also, it would be nice to install the dependabot GitHub app to help keep dependencies up to date, but I don't think I have permissions to do that.

**Comment by khuey** [comment]
Both should be done now.

**Comment by djc** [comment]
Yup, thanks!

**Comment by khuey** [comment]
I just noticed that I'm still an owner of the bb8 crates on crates.io. Unless you for some reason object, I'm going to remove myself next week.

**Comment by djc** [comment]
Seems fine!

**Comment by khuey** [comment]
And of course I screwed up and removed you from one of them, so you'll need to reaccept the invitation.
