### ISSUE TITLE
add redis example

### ISSUE THREAD

**Issue by uvd** [khuey/bb8#52]

**Comment by uvd** [comment]
`rust

31 |     let mut   conn =  sta.redis.get().await.unwrap().unwrap();
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                       |
   |                       move occurs because value has type `std::option::Option<redis::aio::Connection>`, which does not implement the `Copy` trait
   |                       help: consider borrowing the `Option`'s content: `sta.redis.get().await.unwrap().as_ref()`


`

**Comment by djc** [comment]
Try with `as_mut().unwrap()`?

**Comment by pksunkara** [comment]
This worked. You can close this.

**Comment by djc** [comment]
Thanks for following up!

**Comment by pksunkara** [comment]
I am not the OP, but I go the same error.

**Comment by djc** [comment]
Ah, ok. Thanks anyway!
