### ISSUE TITLE
bb8 leaks connection if executor stops polling (e.g. on timeout)

### ISSUE THREAD

**Issue by kodieg** [khuey/bb8#59]
I added timeout to code that connect to redis and sends a few commands using tokio::time::timeout. That works just by stopping polling future produced by pool().get(). Unfortunately bb8 leaks connections in certain cases, and after some time pool is empty and not usable.

One of problems is here in the get function below (bb8/src/lib.rs).
```rust
pub async fn get(&self) -> Result<PooledConnection<'_, M>, RunError<M::Error>> {
        let conn = self.get_conn::<M::Error>().await?;
        Ok(PooledConnection {
            pool: self,
            checkout: Instant::now(),
            conn: Some(conn),
        })
    }
```

 Polling may be stopped between await and construction of PooledConnection. Thus connection is leaked. 

This problem may be solved I think by replacing this implementation with:
```rust
    pub async fn get(&self) -> Result<PooledConnection<'_, M>, RunError<M::Error>> {
        let conn = self.get_conn::<M::Error>();

        conn.map(move |conn_result| {
            conn_result.map(|conn| {
                PooledConnection {
                    pool: self,
                    checkout: Instant::now(),
                    conn: Some(conn),
                }
            })
        }).await
    }
```

However, I think also get_conn internally may have this provlem whem validation is enabled. Maybe one solution would be to create PooledConnection as soon as it is removed from popped from `conns`:
```rust
if let Some(conn) = internals.conns.pop_front() {
```

**Comment by djc** [comment]
Sorry for taking so long on this -- I was wondering about larger solutions to the problem, but in the end fixing the leakage in `get()` is fairly straightforward.

For validation in `get_conn()`, the `M::Connection`'s ownership is passed to the validator, so in that case there's nothing we can do within the constraints of the current API. Potentially the validation API could take a reference instead, but I need to think more about the implications of that.
