### ISSUE TITLE
Change `is_valid()` to take a mutable Self::Connection, instead of accepting then returning an owned value?

### ISSUE THREAD

**Issue by naerbnic** [khuey/bb8#63]
It's conceivable that, even in a case where a connection is no longer valid, that other parts of the connection manager may want to access the connection value. For instance, the r2d2 CustomizeConnection trait will pass that to on_release(), which can perform more custom operations on it. Is there any reason, aside from backwards compatibility, that `is_valid()` does not take Self::Connection by mutable reference, then have the Result be `Result<(), Self::Error>`? I believe this would better deal with the circumstances, and still permit the connection itself to be dropped.

**Comment by djc** [comment]
Yeah, I think that would make sense. Would you be interested in implementing this?

**Comment by naerbnic** [comment]
Certainly. I have a version ready to go. I'll send it over shortly.

**Comment by djc** [comment]
Fixed in #64.
