### ISSUE TITLE
compile error ,maybe tokio-postgers update

### ISSUE THREAD

**Issue by blueskyisgood** [khuey/bb8#7]
struct `Error` is private
  --> postgres/src/lib.rs:13:34
   |
13 | use tokio_postgres::{Connection, Error, TlsMode};
   |                                  ^^^^^

error[E0599]: no function or associated item named `connect` found for type `tokio_postgres::Connection` in the current scope
  --> postgres/src/lib.rs:50:9
   |
50 |         Connection::connect(self.params.clone(), (self.tls_mode)(), &handle)
   |         ^^^^^^^^^^^^^^^^^^^ function or associated item not found in `tokio_postgres::Connection`

error[E0599]: no method named `batch_execute` found for type `tokio_postgres::Connection` in the current scope
  --> postgres/src/lib.rs:57:14
   |
57 |         conn.batch_execute("")
   |              ^^^^^^^^^^^^^

error[E0599]: no method named `is_desynchronized` found for type `&mut tokio_postgres::Connection` in the current scope
  --> postgres/src/lib.rs:61:14
   |
61 |         conn.is_desynchronized()
   |              ^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

**Comment by khuey** [comment]
Yeah, I should have pinned a specific version of tokio-postgres in the Cargo.toml.

I'll take a look at this.

**Comment by khuey** [comment]
The crate should compile now.

**Comment by blueskyisgood** [comment]
Now can compile,Thanks.
