### ISSUE TITLE
stucked server 

### ISSUE THREAD

**Issue by invis87** [khuey/bb8#84]
In current project my team needs a middleware service between redis and rest of the world. So I wrote one that use bb8-redis under the hood, but unfortunately it stucks under a lot of connections.

I create repo with instructions how to reproduce, [here it is](https://github.com/invis87/bb8_redis_stuck).

**Comment by invis87** [comment]
with `mobc` pool all works fine!

**Comment by djc** [comment]
I don't have an easy test environment, but I just spent quite a bit of time to improve the implementation. Please test current master and let me know if it works better for you.

**Comment by djc** [comment]
Going to close this as a duplicate of #67 for now.

**Comment by invis87** [comment]
No longer reproducible.
Good job!

**Comment by djc** [comment]
Thanks for testing!
