### ISSUE TITLE
Use tokio-postgres optional features

### ISSUE THREAD

**Issue by petereast** [khuey/bb8#9]
Just a quick question - is there a way to enable some optional features of `tokio-postgres`? And if so, how would  I do it?  

We're getting the following error:
```the package `event-store` depends on `bb8-postgres`, with features: `with-uuid, with-chronos, with-serde_json` but `bb8-postgres` does not have these features.```
Enabling those features for the `tokio_postgres` crate and using a `bb8::Pool` doesn't work, so we were wondering if this could be due to the bb8's internal use of `tokio_postgres` not including those features? Do you have any advice on what we should do?

**Comment by khuey** [comment]
9f7d763b55211001d8168ebfde449d8b0d0614f6 adds feature flags to `bb8-postgres` that correspond to the `tokio-postgres` feature flags of the version we're using, and passes them through to `tokio-postgres`.

Let me know if you have any addition problems.

**Comment by petereast** [comment]
Wow that was quick! Thank you very much!

**Comment by khuey** [comment]
As you can probably tell from the change it wasn't hard :) I just haven't had anyone ask for it yet.
